name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: npm run build
        env:
          VITE_OPENAI_API_KEY: ${{secrets.VITE_OPENAI_API_KEY}}
